social_media:
  facebook_share:
    text: 'Jaa Facebook-palvelussa'
    api_url: 'https://www.facebook.com/share.php?u=[current-page:url]&title=[current-page:title]'
  linkedin:
    api_url: 'https://www.linkedin.com/sharing/share-offsite/?url=[current-page:url]'
    text: 'Jaa LinkedIn-palvelussa'
  twitter:
    api_url: 'https://x.com/intent/post?url=[current-page:url]&status=[current-page:title]+[current-page:url]'
    text: 'Jaa X-palvelussa'
  email:
    text: 'Lähetä sivu sähköpostitse'
  print:
    text: Print
