social_media:
  facebook_share:
    text: 'Dela på Facebook'
  linkedin:
    api_url: 'https://www.linkedin.com/sharing/share-offsite/?url=[current-page:url]'
    text: 'Dela på LinkedIn'
  twitter:
    api_url: 'https://x.com/intent/post?url=[current-page:url]&status=[current-page:title]+[current-page:url]'
    text: 'Dela på X'
  pinterest:
    text: Pinterest
  email:
    text: 'Skicka sidan via e‑post'
  print:
    text: Print
